version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    image: template-project-frontend:latest
    ports:
      - ${FRONTEND_PORT}:80

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    image: template-project-backend:latest
    ports:
      - ${BACKEND_PORT}:3000
